name: Selenium Test Workflow

on: push

jobs:
  Selenium_Test_Job1:
    name: Selenium Test Job 1
    runs-on: windows-latest
    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in Github"
      - name: Check out source code
        uses: actions/checkout@v4.1.7
      - run: echo "This repo is ${{ github.repository }}"
      - name: Run inline script
        run: |
          mkdfdsir newfloder
          ls -l
        shell: bash
      - name: Run a script file from repo
        if: ${{ always() }}
        run: sh ./run.sh
        shell: pwsh
      - name: Execute during failure
        if: ${{ failure() }}
        run: echo "One of the steps has failed"
        shell: pwsh

  Selenium_Test_Job2:
    name: Selenium Test Job 2
    runs-on: ubuntu-latest
    needs: Selenium_Test_Job1 
    if: ${{ always() }}

    steps:
      - run: echo "This is from second job"
      
      
