name: PULL REQUEST TO MASTER

on: 
  pull_request:
    branches: [ master ]

jobs:
  Job1:
    name: Pull Request 1
    runs-on: windows-latest
    env: 
      SELENIUM_DRIVER: 'RemoteWebDriver'
    
    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in Github"
      - run: echo "The code is owned by ${{ github.repository_owner}}"
      - name: Check out source code
        uses: actions/checkout@v4.1.7
      - run: echo "This repo is ${{ github.repository }}"
      - name: Run inline script
        run: |
          mkdir newfolder
          ls -l
        shell: bash
      - name: Run a script file from repo
        if: ${{ always() }}
        run: sh ./run.sh
        shell: pwsh
      - name: Execute during failure
        if: ${{ failure() }}
        run: echo "One of the steps has failed"
        shell: pwsh
      - name: Run Selenium Test
        if: ${{ env.SELENIUM_DRIVER == 'RemoteWebDriver'}}
        run: echo "Running test in Selenium grid setup"

  Job2:
    name: Pull Request 2
    runs-on: ubuntu-latest
    needs: Job1 
    if: ${{ always() }}

    steps:
      - run: echo "This is from second job"
      
      
