name: PUSH INTO MASTER

on: 
  push:
    branches: [ master ]

jobs:
  Selenium_Test_Job1:
    name: Selenium Test Job 1
    runs-on: windows-latest
    env: 
      SELENIUM_DRIVER: 'RemoteWebDriver'
    
    steps:
      - run: echo "Push from ${{ github.ref}} branch into master"
      - run: echo "This is running inside a ${{ runner.os }} server in Github"
      - run: echo "The code is owned by ${{ github.repository_owner}}"
      - name: Check out source code
        uses: actions/checkout@v4.1.7
      - run: echo "This repo is ${{ github.repository }}"
      - name: Run Selenium Test
        if: ${{ env.SELENIUM_DRIVER == 'RemoteWebDriver'}}
        run: echo "Running test in Selenium grid setup"

      
